// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOgizUSx7Sx4RudGJH841N0ODjepjMl4',
    appId: '1:519653301005:web:0022c8a20cf01feab7ae44',
    messagingSenderId: '519653301005',
    projectId: 'siosapp-335118',
    authDomain: 'siosapp-335118.firebaseapp.com',
    databaseURL: 'https://siosapp-335118-default-rtdb.firebaseio.com',
    storageBucket: 'siosapp-335118.appspot.com',
    measurementId: 'G-0FQ0WFXJGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6SrNElBbvIVhJtW3t_K4cn8OasyznsQ',
    appId: '1:519653301005:android:5f711aae2746887cb7ae44',
    messagingSenderId: '519653301005',
    projectId: 'siosapp-335118',
    databaseURL: 'https://siosapp-335118-default-rtdb.firebaseio.com',
    storageBucket: 'siosapp-335118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PrVNWoEKyd_seinApH7_6Twkrfz65Cs',
    appId: '1:519653301005:ios:61c6c1c4193e7fbfb7ae44',
    messagingSenderId: '519653301005',
    projectId: 'siosapp-335118',
    databaseURL: 'https://siosapp-335118-default-rtdb.firebaseio.com',
    storageBucket: 'siosapp-335118.appspot.com',
    iosClientId: '519653301005-h58ulhr6q7spo31vri26g52mfkhohfdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
